export enum AccountType {
  CASH = 'CASH',
  DEBIT_CARD = 'DEBIT_CARD',
  CREDIT_CARD = 'CREDIT_CARD',
  VIRTUAL_ACCOUNT = 'VIRTUAL_ACCOUNT',
  INVESTMENT = 'INVESTMENT',
  RECEIVABLES = 'RECEIVABLES',
  PAYABLES = 'PAYABLES',
};
